<!DOCTYPE html>
<html lang="pl">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Navigation class example</title>

<link href="<?= $path; ?>css/bootstrap.css" rel="stylesheet">
<link href="<?= $path; ?>css/navigation.css" rel="stylesheet">
<link href="<?= $path; ?>css/topmenu.css" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

	<header>

		<div class="mainMenu" id="mainMenuContainer">
    		<?= $navigationOutput; ?>
    	</div>

	</header>


	<div class="content container">
	
	<p class="bg-info" style="padding:5px">
	   Źródło: <a href="https://github.com/motarny/Navigation/tree/master/lib/Navigation" target="_blank">github.com/motarny/Navigation</a>
	</p>

		<div class="row">

			<div class="pull-right" style="margin: 10px">
	
	<?php if (($actionIndex < @$maxAction) || ($actionIndex == 0)) : ?>
	<a
					href="<?php $actionIndex == 0 ? print('actions/') : null; ?>action<?= $actionIndex + 1; ?>.php">
					<button type="button" class="btn btn-primary btn-sm">Dalej</button>
				</a>
	<?php endif; ?>

    	
    	</div>

			<div class="pull-left" style="margin: 10px">
	
	<?php if ($actionIndex != 0) : ?>
	<a href="../index.php">
					<button type="button" class="btn btn-danger btn-sm">Restart</button>
				</a>
	<?php endif; ?>

    	
    	</div>

		</div>

		<div class="row" style="margin-top: 20px; padding-bottom:15px;">

			<div class="navigationStructure col-md-4 col-lg-4">
				<h4>Nieostylowana struktura nawigacji</h4>
				<div class="content">
	    			<?= $navigationOutput; ?>
    				
    			</div>
			</div>

			<div class="navigationSource col-md-8 col-lg-8">
				<h4>Tablica źródła nawigacji (do konstruktora)</h4>
				<div class="content" style="overflow: auto;">
    				<?php
        $navigationSource = $navigation->getNavigationArrayAsString();
        echo nl2br(str_replace(" ", "&nbsp;", $navigationSource));
        ?>
    			</div>
			</div>

		</div>

		<div class="row" style="margin-top: 40px">

			<div class="actionsContainer">

				<div class="action">
    			 <?php
        if ($actionIndex == 0) {
            include 'actions/descr' . $actionIndex . '.html';
        } else {
            include 'descr' . $actionIndex . '.html';
        }
        ?>
    			</div>

			</div>
		</div>


			<p>
	
	<?php if (($actionIndex < @$maxAction) || ($actionIndex == 0)) : ?>
	<a
			href="<?php $actionIndex == 0 ? print('actions/') : null; ?>action<?= $actionIndex + 1; ?>.php">
			<button type="button" class="btn btn-primary btn-lg center-block">Dalej</button>
		</a>
	<?php endif; ?>

	</p>
		
	</div>


	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="<?= $path; ?>js/bootstrap.min.js"></script>


	<script>



	</script>


</body>
</html>

